<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_Register</name>
   <tag></tag>
   <elementGuidId>9635f901-a8f5-4fe8-b0ff-9acaa360f787</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='um-submit-btn']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#um-submit-btn</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9d937590-14fc-4b18-b45c-d6202b769ecb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>4b3810a1-5370-4b64-83e0-6b5874fc0c4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Register</value>
      <webElementGuid>b58e01f1-01e5-40ca-8012-17078dd09694</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>um-button</value>
      <webElementGuid>6904a700-17c2-4691-9d52-d8b1b219bfde</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>um-submit-btn</value>
      <webElementGuid>70ff16a9-1ea6-468e-8879-38d3ff557058</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;um-submit-btn&quot;)</value>
      <webElementGuid>0c8fba0f-efc9-43a0-8a76-b7621fe8f506</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='um-submit-btn']</value>
      <webElementGuid>50ee76ce-7839-4400-bd10-e50058639be4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//article[@id='post-301']/div/figure/table/tbody/tr/td/div/div/form/div[2]/div/input</value>
      <webElementGuid>9fe92853-4284-4148-9342-bb3b6bee3516</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>c71470da-5c0d-431f-b008-2c72e7fafb5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @id = 'um-submit-btn']</value>
      <webElementGuid>7f133ede-d2fe-4446-8bdc-f8532305e064</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
