<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_AlbumProduct</name>
   <tag></tag>
   <elementGuidId>9b954553-466b-486f-a382-563299d6e52c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='sticky_bottom_anchor']/ul/li[2]/div/div/div[2]/a/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.attachment-woocommerce_thumbnail.size-woocommerce_thumbnail</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>a1dd7629-ba54-4b91-b693-5ac1854e1710</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>330</value>
      <webElementGuid>7f11f3f5-17f8-45f3-b616-4330209f5f70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>413</value>
      <webElementGuid>fe8a8d27-d768-4384-ba80-37dbe76f0869</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://kotakoki.wijaysali.my.id/wp-content/uploads/2022/06/IMG-20220606-WA0002-330x413.jpg</value>
      <webElementGuid>fc5b9d65-e725-434a-b136-45d45c3d70c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>attachment-woocommerce_thumbnail size-woocommerce_thumbnail</value>
      <webElementGuid>1e07cb01-260a-4f31-8adc-e5e80bbb7ed6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>816f69e5-dd4b-435d-8398-2cf6e1d67cab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>https://kotakoki.wijaysali.my.id/wp-content/uploads/2022/06/IMG-20220606-WA0002-330x413.jpg 330w, https://kotakoki.wijaysali.my.id/wp-content/uploads/2022/06/IMG-20220606-WA0002.jpg 333w</value>
      <webElementGuid>0b955fbe-a083-4af9-9c05-366d0a696fa8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sizes</name>
      <type>Main</type>
      <value>(max-width: 330px) 100vw, 330px</value>
      <webElementGuid>536ee6f0-3acf-4b38-8656-0af5cb35da80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sticky_bottom_anchor&quot;)/ul[@class=&quot;products columns-3 js_animated&quot;]/li[@class=&quot;product type-product post-17 status-publish first instock product_cat-uncategorized has-post-thumbnail downloadable virtual purchasable product-type-simple visible animation_ready animated&quot;]/div[@class=&quot;main-container&quot;]/div[@class=&quot;product_image_wrapper&quot;]/div[@class=&quot;product_image&quot;]/a[1]/img[@class=&quot;attachment-woocommerce_thumbnail size-woocommerce_thumbnail&quot;]</value>
      <webElementGuid>8aeddbfa-c22d-4a05-bdee-3349cf1abe2d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sticky_bottom_anchor']/ul/li[2]/div/div/div[2]/a/img</value>
      <webElementGuid>e7d7f0e1-a0a1-4c2b-a474-51ed2ab7a65c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://kotakoki.wijaysali.my.id/wp-content/uploads/2022/06/IMG-20220606-WA0002-330x413.jpg')]</value>
      <webElementGuid>4457e9f5-472c-4ce2-bdd2-ccd938ac31e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/a/img</value>
      <webElementGuid>4c58638d-e058-49fb-a0ad-934676085c93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://kotakoki.wijaysali.my.id/wp-content/uploads/2022/06/IMG-20220606-WA0002-330x413.jpg']</value>
      <webElementGuid>eda24f10-68eb-4d53-b5fc-869cb28a6b74</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
